### PR TITLE
Linaro builds switched to manylinux2014

### PR DESCRIPTION
**Pull request by hrw**
After several requests for package for Python newer than 3.6/3.7 I rewrote CI jobs to use manylinux2014 container image.

We are now building 1.x, 2.4.x, 2.5.x and git HEAD versions.

Released ones are built when needed and only for selected versions so you need to check separate directories for wheel files. Git HEAD is built daily.

### CODE REVIEW

**Comment by hrw** [comment]
We now provide:


TensorFlow version | Python 3.6 | Python 3.7 | Python 3.8 | Python 3.9
-- | -- | -- | -- | --
1.15.5 | OK | OK | – | –
2.4.1 | OK | OK | OK | OK
2.5.0 | OK | OK | OK | OK
git HEAD | OK | OK | OK | OK

**Comment by angerson** [comment]
Excellent. This is timely. Thank you @hrw!

Can you please send angerson@google.com a primary and backup email contact for these builds?

**Comment by hrw** [comment]
@angerson done

**Review by angerson — APPROVED** [review]
Thanks!

**Pull request merged**
