### PR TITLE
Separate dev baseline and cuda layers

### PR DESCRIPTION
**Pull request by bhack**
This pull request is going to separate baseline and GPU layers to conditionally build GPU and GPU images with a subsequent PR.

See more at:
https://discuss.tensorflow.org/t/adopting-open-source-dockerfiles-for-official-tf-nightly-ci/6050/4
https://github.com/tensorflow/addons/issues/2613

### CODE REVIEW

**Comment by angerson** [comment]
What, specifically, could be accomplished with this change that could not be done with the current set of images?

**Comment by bhack** [comment]
It was discussed already in the forum thread and in the mentioned ticket.
With we have an intermediate CPU/baseline only image/target without the mandatory 4.24 GB single layer that includes CUDA.
In many use cases we don't want to handle the overhead to invalidate a 4.24 layer (re-download, extract and disk space or cloud occupancy).

The CPU/baseline could be also useful later to create other kind of images that are note CUDA centric.. eg. ROCM etc..

Preparing many PR doesn't requires the CUDA  overhead and could be prepared on CPU only machine with a baseline image. Also If you develop your PR  on the cloud you could just save disk space/costs.

We need to support developers diversity and this is not going to create a tool large overhead and it is simply an intermediate stage/target over the original design.

**Comment by angerson** [comment]
Ok, let's put this idea on hold until the size prevents us from doing something we otherwise would do. For example, if we're unable to run tests or provide some other utility because the size of the container is too large. For this quarter, I am restricting all development on these images to what my team uses in CI. Our CI doesn't need small CPU images, so any work towards those is going to create dead / unsupported extra containers, which I'm not willing to do until we have a lot more information about usage, needs, etc.

**Comment by bhack** [comment]
If [6 years](https://github.com/tensorflow/tensorflow/issues/5#issuecomment-158736482) of activity in TF are not enough for you to support this it is ok.
But I think that it will be hard to find longer contributors when you are going to  evaluate `community` maintanership:
immagine

**Comment by bhack** [comment]
This was gone a little bit on drift over the time cause we had other commit on master. 
In general I don't know if @deven-amd could be interested in this separation.

**Comment by bhack** [comment]
As nobody is interested to reuse a common and shared CPU stage/image baseline I'am going to close this.

**Pull request closed without merging**
