### PR TITLE
Pylint and sanity_check

### PR DESCRIPTION
**Pull request by bhack**
This is a github Action to support and test https://github.com/tensorflow/tensorflow/pull/48294 and our Gitter thread with /cc @perfinion @angerson. It has two job flat `pylint` and `ci_sanity.sh` in `tensorflow/tensorflow:devel`.

As you can see from the Action log `pylint` behavior is different if we let it to explore the module itself or if we push a list of python files with `find` as in our `ci_sanity.sh` approach.

See also:
https://stackoverflow.com/questions/36873096/run-pylint-for-all-python-files-in-a-directory-and-all-subdirectories
https://pylint.readthedocs.io/en/latest/user_guide/run.html

### CODE REVIEW

**Comment by angerson** [comment]
What's the end goal for this PR? It doesn't seem useful for this repo.

**Comment by bhack** [comment]
The goal of this PR is not to be merged but fast iterate using thr Action and understand how we want to execute pylint on the developer machine having the same results as Ubuntu Sanity VM where I have no visibility.

**Comment by Pierre-Sassoulas** [comment]
I did not check everything but pylint need ``__init__.py`` to analyse a module, a directory without one won't be analysed. But a file given directly to pylint in such a directory will.

**Comment by bhack** [comment]
@Pierre-Sassoulas  I think I've found the issue. With wildcard import :
```
from tensorflow.python.ops.control_flow_ops import *
```
The `pylint: disable=redefined-builtin` in the imported `control_flow_ops` file is ignored and you got `W0622`.

If you direct import 
```
from tensorflow.python.ops import control_flow_ops
```
the `pylint: disable=redefined-builtin` in `contro_flow_ops` it seems respected.

**Comment by bhack** [comment]
@angerson Can you let run the Action?

**Comment by bhack** [comment]
Also we need have an outcome from the dev-infra team related to https://github.com/tensorflow/build/pull/27#issuecomment-827819407

**Comment by bhack** [comment]
Can you re-run this Action?

**Comment by Pierre-Sassoulas** [comment]
You can close and reopen to launch the check again

**Comment by bhack** [comment]
I don't think that we have this policy but I will try.

**Pull request closed without merging**
