### PR TITLE
Add TPU configs

### PR DESCRIPTION
**Pull request by chandrasekhard2**
With the introduction of TF-TPU whls, we're adding corresponding TF-TPU Docker configs.

### CODE REVIEW

**Review by MichaelHudgins — CHANGES_REQUESTED** [review]
Small nit but can you verify copyright dates if this is the first time these files are new

**Comment by chandrasekhard2** [comment]
> Small nit but can you verify copyright dates if this is the first time these files are new

Done

**Review by MichaelHudgins — APPROVED** [review]

**Review by onlykash1 — COMMENTED** [review]
good

**Comment by onlykash1** [comment]
gg

**Comment by onlykash1** [comment]
hh

**Pull request merged**
