### PR TITLE
Add ssh client support

### PR DESCRIPTION
**Pull request by bhack**

### CODE REVIEW

**Comment by angerson** [comment]
Can you explain why this is necessary?

**Comment by bhack** [comment]
It is the same as the one merged few weeks ago at https://github.com/tensorflow/build/pull/85

Mainly we need to have a ssh client ready to authenticate/interact with Github (e.g. `git push` etc..)

**Comment by angerson** [comment]
Ok, that's good to know for the future when we look at making this more useful for that purpose.

**Comment by bhack** [comment]
> Ok, that's good to know for the future when we look at making this more useful for that purpose.

Ok but I suppose you know as we have already 27 entries in TF "official" Dockerfiles:
https://github.com/tensorflow/tensorflow/search?l=Dockerfile&q=openssh-client

**Pull request closed without merging**
